POST http://localhost:5000/todos HTTP/1.1
Content-Type: application/json

{
    "description": "I need to clean my room."
}

GET http://localhost:5000/todos HTTP/1.1

GET http://localhost:5000/todos/1 HTTP/1.1

PUT http://localhost:5000/todos/1 HTTP/1.1
Content-Type: application/json

{
    "description": "I need to fix my life."
}

DELETE http://localhost:5000/todos/5 HTTP/1.1